config/routes.rb
Rails.application.routes.draw do

	resources :books do
		member do
			get :delete
		end
	end

  root 'books#index'
  get 'books/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	scope :sorted, lambda { order("title ASC") }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book created successfully."
      redirect_to(books_path)
    else
      render('new')
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update_attributes(book_params)
      flash[:notice] = "Book updated successfully."
      redirect_to(book_path(@book))
    else
      render('edit')
    end
  end

  def delete
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "Book '#{@book.title}' destroyed successfully."
    redirect_to(books_path)
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :genre, :price, :publisheddate)
  end

end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/views/books/delete.html.erb
<%= link_to("<< Back to List", books_path, :class => 'back-link') %>

<div class="books delete">
	<h2>Delete Book</h2>
	<%= form_for(@book, :method => 'delete') do |f| %>

	<p>Are you sure you want to permanently delete this book?</p>

	<p class="reference-name"><%= f.object.title %></p>

	<div class="form-buttons">
		<%= f.submit("Delete Book") %>
	</div>

	<% end %>
</div>

app/views/books/edit.html.erb
<%= link_to("<< Back to List", books_path, :class => 'back-link') %>

<div class="books edit">
	<h2>Update Book</h2>

	<%= form_for(@book) do |f| %>


	<table summary="Book form fields">
		<tr>
			<th>Title</th>
			<td><%= f.text_field(:title) %></td>
		</tr>
		<tr>
			<th>Author</th>
			<td><%= f.text_field(:author) %></td>
		</tr>
		<tr>
			<th>Genre</th>
			<<td><%= f.select(:genre, ['Drama', 'Thriller', 'Comedy', 'Romance']) %></td>
		</tr>
		<tr>
			<th>Price</th>
			<td><%= f.text_field(:price) %></td>
		</tr>
		<tr>
			<th>Published Date</th>
			<td><%= f.date_field(:publisheddate, :locale => 'en') %></td>
		</tr>
	</table>

	<div class="form-buttons">
		<%= f.submit("Update Book") %>
	</div>

	<% end %>
</div>

app/views/books/index.html.erb
<% if !flash[:notice].blank? %>
<div class="notice">
	<%= flash[:notice] %>
</div>
<% end %>


<div class="books index">
	<h2>Books</h2>


	<%= link_to("Add New Book", new_book_path, :class => 'action new') %>


	<table class="listing" summary="Book list">
		<tr class="header">
			<th>Title</th>
			<th>Author</th>
			<th>Genre</th>
			<th>Price</th>
			<th>Published Date</th>
			<th>Actions</th>
		</tr>
		<% @books.each do |book| %>
		<tr>
			<td><%= book.title %></td>
			<td class="center"><%= book.author %></td>
			<td class="center"><%= book.genre %></td>
			<td class="center"><%= book.price %></td>
			<td class="center"><%= book.publisheddate %></td>
			<td class="actions">
				<%= link_to("Show", book_path(book), :class => 'action show') %>
				<%= link_to("Edit", edit_book_path(book), :class => 'action edit') %>
				<%= link_to("Delete", delete_book_path(book), :class => 'action delete') %>
			</td>
		</tr>
		<% end %>
	</table>
</div>

app/views/books/new.html.erb
<%= link_to("<< Back to List", books_path, :class => 'back-link') %>

<div class="books new">
	<h2>Create Book</h2>

	<%= form_for(@book, :url => books_path, :method => 'post') do |f| %>


	<table summary="Book form fields">
		<tr>
			<th>Title</th>
			<td><%= f.text_field(:title) %></td>
		</tr>
		<tr>
			<th>Author</th>
			<td><%= f.text_field(:author) %></td>
		</tr>
		<tr>
			<th>Genre</th>
			<td><%= f.select(:genre, ['Drama', 'Thriller', 'Comedy', 'Romance']) %></td>
		</tr>
		<tr>
			<th>Price</th>
			<td><%= f.text_field(:price) %></td>
		</tr>
		<tr>
			<th>Published Date</th>
			<td><%= f.date_field(:publisheddate, :locale => 'en') %></td>
		</tr>
	</table>

	<div class="form-buttons">
		<%= f.submit("Create Book") %>
	</div>

	<% end %>
</div>

app/views/books/show.html.erb
<% if !flash[:notice].blank? %>
<div class="notice">
	<%= flash[:notice] %>
</div>
<% end %>

<%= link_to("<< Back to List", books_path, :class => 'back-link') %>

<div class="books show">
	<h2>Show Book</h2>


	<table summary="Book detail view">
		<tr>
			<th>Title</th>
			<td><%= @book.title %></td>
		</tr>
		<tr>
			<th>Author</th>
			<td><%= @book.author %></td>
		</tr>
		<tr>
			<th>Genre</th>
			<td><%= @book.genre %></td>
		</tr>
		<tr>
			<th>Price</th>
			<td><%= @book.price %></td>
		</tr>
		<tr>
			<th>Published Date</th>
			<td><%= @book.publisheddate %></td>
		</tr>
	</table>

</div>

app/views/demo/index.html.erb
<h1>Demo#index</h1>
<p>Find me in app/views/demo/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>